### ISSUE TITLE
Great app

### ISSUE THREAD

**Issue by mrobertsn** [cho45/NanoVNA-WebUSB-Client#1]
I love the app, great idea and great work on it. Perhaps you have probably already thought about it, but a TDR feature would go nice with it, similar to this - https://nuclearrambo.com/wordpress/accurately-measuring-cable-length-with-nanovna/

**Comment by Lusitanv** [comment]
OP, congrats for the interface. I will keep following it.

**Comment by cho45** [comment]
[![Image from Gyazo](https://i.gyazo.com/161c5e0e72c78d97c246f9dc3e1e26ad.png)](https://gyazo.com/161c5e0e72c78d97c246f9dc3e1e26ad)

TDR implemented

**Comment by Lusitanv** [comment]
Outstanding.

Thank you!

**Comment by mrobertsn** [comment]
Awesome
