### ISSUE TITLE
Offline Usage

### ISSUE THREAD

**Issue by Lusitanv** [cho45/NanoVNA-WebUSB-Client#2]
Hello,

How can we install the client to run standalone/offline/no internet access?

Cheers

**Comment by cho45** [comment]
currently no. It would be possible to install app online and use app offline (with ServiceWorker), but there is no plan for now.

**Comment by Lusitanv** [comment]
OK, but why cant we simply replicate whats running on https://cho45.stfuawsc.com/NanoVNA/ in a local webserver?
Can you share the server side?
Cheers and thanks

**Comment by cho45** [comment]
yes, you can do it. There ia no server side impl. So, you can just launch static web server.
