### ISSUE TITLE
Strange spikes

### ISSUE THREAD

**Issue by mikerobertsn** [cho45/NanoVNA-WebUSB-Client#5]
Hi, when running a logmag plot i get random frequency spikes which go to zero which aren’t on the nanovna screen, looks like a bit of a bug.

**Comment by cho45** [comment]
It is fixed on this commit: https://github.com/ttrftech/NanoVNA/commit/197fd38862c14761fd95c3caf66d22a7a2fe5a9d .

You need to update firmware to latest one.
